### ISSUE TITLE
occasional static in total snes audio payload

### ISSUE THREAD

**Issue by Ownasaurus** [Ownasaurus/TAStm32#7]
-Ofast, very rare but happens

**Comment by compucat** [comment]
Notes from stream so they're not forgotten:
Might potentially be fixed by moving vis board update code out of critical interrupt
Disabling optimizations entirely is too slow for audio at all
Potentially look into GCC syntax to explicitly prevent the inline asm from being optimized (instead of getting lucky with moving it into an else clause)

**Comment by Ownasaurus** [comment]
Resolved with cca18c4fea3b4b86255974b23f5d309aa6baff13

**Comment by Ownasaurus** [comment]
Still occurs, but not commonly. Occurs almost exactly every 1 minute and 22 seconds. Needs further investigation.

**Comment by Ownasaurus** [comment]
Actually resolved with 1cd756c9cab559a89cffeb8d6fa63a3e1aff6a26 ;)
